ALTER TABLE APPOINTMENT DROP FOREIGN KEY FK_APPOINTMENT_id_assistito
ALTER TABLE MEETING DROP FOREIGN KEY FK_MEETING_PERSON_ID
DROP TABLE APPOINTMENT
DROP INDEX Assisted_Index_SurnameName ON ASSISTED
DROP INDEX Assisted_Index_Name ON ASSISTED
DROP TABLE ASSISTED
DROP TABLE MEETING
DROP TABLE settings
